import { useRef } from "react";

const SCORE_LABELS = {
  communication: "Communication",
  technical:     "Technical",
  clarity:       "Clarity",
  confidence:    "Confidence",
};

const VERDICT_STYLE = {
  "Strong Hire": { bg: "rgba(74,222,128,0.1)", border: "#4ade80", text: "#4ade80", emoji: "🚀" },
  "Hire":        { bg: "rgba(74,222,128,0.07)", border: "#22c55e", text: "#22c55e", emoji: "✅" },
  "Borderline":  { bg: "rgba(251,191,36,0.1)", border: "#fbbf24", text: "#fbbf24", emoji: "⚖️" },
  "No Hire":     { bg: "rgba(255,107,107,0.1)", border: "#ff6b6b", text: "#ff6b6b", emoji: "📚" },
};

function ScoreBar({ label, score }) {
  const pct = (score / 10) * 100;
  const color = score >= 7.5 ? "#4ade80" : score >= 5 ? "#fbbf24" : "#ff6b6b";
  return (
    <div style={{ marginBottom: "14px" }}>
      <div style={{ display: "flex", justifyContent: "space-between", marginBottom: "6px" }}>
        <span style={{ fontSize: "13px", color: "var(--text)" }}>{label}</span>
        <span style={{ fontSize: "13px", fontWeight: 700, color }}>{score} / 10</span>
      </div>
      <div style={{ height: 8, background: "var(--border)", borderRadius: 4, overflow: "hidden" }}>
        <div style={{
          height: "100%", width: `${pct}%`, borderRadius: 4,
          background: `linear-gradient(90deg, ${color}99, ${color})`,
          transition: "width 1s ease",
        }} />
      </div>
    </div>
  );
}

export default function FeedbackScreen({ feedback, role, onRestart }) {
  const printRef = useRef(null);

  if (!feedback) return null;

  const { overallScore, scores, strengths, improvements, summary, verdict } = feedback;
  const vStyle = VERDICT_STYLE[verdict] || VERDICT_STYLE["Borderline"];
  const overallPct = (overallScore / 10) * 100;
  const overallColor = overallScore >= 7.5 ? "#4ade80" : overallScore >= 5 ? "#fbbf24" : "#ff6b6b";

  function handlePrint() {
    const el = printRef.current;
    const html = `<!DOCTYPE html><html><head>
      <meta charset="utf-8"/>
      <title>Interview Feedback — ${role}</title>
      <style>
        body { font-family: Arial, sans-serif; background: #fff; color: #111; padding: 32px; max-width: 700px; margin: auto; }
        h1 { font-size: 24px; margin-bottom: 4px; }
        .sub { color: #555; font-size: 13px; margin-bottom: 24px; }
        .score-big { font-size: 52px; font-weight: 800; color: #0097a7; }
        .section { margin-top: 24px; }
        .section h2 { font-size: 15px; font-weight: 700; border-bottom: 2px solid #eee; padding-bottom: 6px; margin-bottom: 12px; }
        .bar-row { margin-bottom: 10px; }
        .bar-label { display: flex; justify-content: space-between; font-size: 13px; margin-bottom: 4px; }
        .bar-bg { height: 8px; background: #eee; border-radius: 4px; }
        .bar-fill { height: 100%; border-radius: 4px; background: #0097a7; }
        ul { padding-left: 18px; }
        li { margin-bottom: 6px; font-size: 13px; line-height: 1.6; }
        .verdict { display: inline-block; padding: 4px 14px; border-radius: 20px; font-weight: 700; font-size: 14px; border: 1.5px solid #0097a7; color: #0097a7; margin-bottom: 12px; }
        p { font-size: 13px; line-height: 1.7; color: #333; }
      </style></head><body>
      <h1>Interview Feedback Report</h1>
      <div class="sub">Role: ${role} · Generated by AI Mock Interviewer</div>
      <div class="verdict">${vStyle.emoji} ${verdict}</div>
      <div class="score-big">${overallScore}<span style="font-size:20px">/10</span></div>
      <div class="section"><h2>Score Breakdown</h2>
        ${Object.entries(scores).map(([k, v]) => `
          <div class="bar-row">
            <div class="bar-label"><span>${SCORE_LABELS[k] || k}</span><span>${v}/10</span></div>
            <div class="bar-bg"><div class="bar-fill" style="width:${(v/10)*100}%"></div></div>
          </div>`).join("")}
      </div>
      <div class="section"><h2>Strengths</h2><ul>${strengths.map(s => `<li>${s}</li>`).join("")}</ul></div>
      <div class="section"><h2>Areas to Improve</h2><ul>${improvements.map(s => `<li>${s}</li>`).join("")}</ul></div>
      <div class="section"><h2>Summary</h2><p>${summary}</p></div>
    </body></html>`;
    const w = window.open("", "_blank");
    w.document.write(html);
    w.document.close();
    w.print();
  }

  return (
    <div className="page">
      <div className="container" style={{ paddingTop: "24px", paddingBottom: "48px" }}>

        {/* Navbar */}
        <nav className="navbar">
          <div className="logo">
            <div className="logo-dot" />
            AI Mock<span>Interviewer</span>
          </div>
          <button className="btn btn-ghost btn-sm" onClick={onRestart}>← New Interview</button>
        </nav>

        {/* Heading */}
        <div className="fade-up" style={{ marginBottom: "28px" }}>
          <h1 style={{ fontSize: "28px", fontWeight: 800, marginBottom: "6px" }}>Your Interview Feedback</h1>
          <p style={{ color: "var(--muted)", fontSize: "14px" }}>Role: <span style={{ color: "var(--teal)" }}>{role}</span></p>
        </div>

        {/* Top row: overall score + verdict */}
        <div className="fade-up" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginBottom: "20px", animationDelay: "0.05s" }}>

          {/* Overall score */}
          <div className="card card-glow" style={{ textAlign: "center", padding: "28px 20px" }}>
            <div style={{ fontSize: "12px", fontWeight: 600, color: "var(--muted)", letterSpacing: "0.5px", marginBottom: "12px" }}>OVERALL SCORE</div>
            {/* Circular progress */}
            <div style={{ position: "relative", width: 100, height: 100, margin: "0 auto 16px" }}>
              <svg width="100" height="100" viewBox="0 0 100 100">
                <circle cx="50" cy="50" r="42" fill="none" stroke="var(--border)" strokeWidth="8" />
                <circle
                  cx="50" cy="50" r="42" fill="none"
                  stroke={overallColor} strokeWidth="8"
                  strokeDasharray={`${2 * Math.PI * 42}`}
                  strokeDashoffset={`${2 * Math.PI * 42 * (1 - overallPct / 100)}`}
                  strokeLinecap="round"
                  transform="rotate(-90 50 50)"
                  style={{ transition: "stroke-dashoffset 1.5s ease" }}
                />
              </svg>
              <div style={{
                position: "absolute", inset: 0, display: "flex",
                flexDirection: "column", alignItems: "center", justifyContent: "center"
              }}>
                <span style={{ fontSize: "26px", fontWeight: 800, color: overallColor }}>{overallScore}</span>
                <span style={{ fontSize: "11px", color: "var(--muted)" }}>/10</span>
              </div>
            </div>
            <div style={{ fontSize: "13px", color: "var(--muted)" }}>
              {overallScore >= 8 ? "Excellent" : overallScore >= 6.5 ? "Good" : overallScore >= 5 ? "Average" : "Needs Work"}
            </div>
          </div>

          {/* Verdict */}
          <div className="card" style={{
            display: "flex", flexDirection: "column", alignItems: "center", justifyContent: "center",
            background: vStyle.bg, border: `1px solid ${vStyle.border}`, padding: "28px 20px", textAlign: "center"
          }}>
            <div style={{ fontSize: "42px", marginBottom: "10px" }}>{vStyle.emoji}</div>
            <div style={{ fontSize: "20px", fontWeight: 800, color: vStyle.text, marginBottom: "6px" }}>{verdict}</div>
            <div style={{ fontSize: "12px", color: "var(--muted)" }}>Hiring Recommendation</div>
          </div>
        </div>

        {/* Score breakdown */}
        <div className="card fade-up" style={{ marginBottom: "16px", animationDelay: "0.1s" }}>
          <h3 style={{ fontSize: "14px", fontWeight: 700, marginBottom: "20px", color: "var(--muted)", letterSpacing: "0.5px" }}>
            SCORE BREAKDOWN
          </h3>
          {Object.entries(scores).map(([key, val]) => (
            <ScoreBar key={key} label={SCORE_LABELS[key] || key} score={val} />
          ))}
        </div>

        {/* Strengths + Improvements */}
        <div className="fade-up" style={{ display: "grid", gridTemplateColumns: "1fr 1fr", gap: "16px", marginBottom: "16px", animationDelay: "0.15s" }}>
          <div className="card" style={{ borderColor: "rgba(74,222,128,0.2)", background: "rgba(74,222,128,0.03)" }}>
            <h3 style={{ fontSize: "13px", fontWeight: 700, color: "#4ade80", letterSpacing: "0.5px", marginBottom: "16px" }}>
              ✓ STRENGTHS
            </h3>
            <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}>
              {(strengths || []).map((s, i) => (
                <li key={i} style={{ display: "flex", gap: "10px", fontSize: "13px", lineHeight: 1.6, color: "var(--text)" }}>
                  <span style={{ color: "#4ade80", flexShrink: 0, marginTop: "1px" }}>→</span>
                  {s}
                </li>
              ))}
            </ul>
          </div>

          <div className="card" style={{ borderColor: "rgba(251,191,36,0.2)", background: "rgba(251,191,36,0.02)" }}>
            <h3 style={{ fontSize: "13px", fontWeight: 700, color: "#fbbf24", letterSpacing: "0.5px", marginBottom: "16px" }}>
              ↑ IMPROVE
            </h3>
            <ul style={{ listStyle: "none", display: "flex", flexDirection: "column", gap: "12px" }}>
              {(improvements || []).map((s, i) => (
                <li key={i} style={{ display: "flex", gap: "10px", fontSize: "13px", lineHeight: 1.6, color: "var(--text)" }}>
                  <span style={{ color: "#fbbf24", flexShrink: 0, marginTop: "1px" }}>→</span>
                  {s}
                </li>
              ))}
            </ul>
          </div>
        </div>

        {/* Summary */}
        <div className="card fade-up" style={{ marginBottom: "24px", animationDelay: "0.2s" }}>
          <h3 style={{ fontSize: "13px", fontWeight: 700, color: "var(--muted)", letterSpacing: "0.5px", marginBottom: "12px" }}>
            📝 OVERALL SUMMARY
          </h3>
          <p style={{ fontSize: "14px", lineHeight: 1.8, color: "var(--text)" }}>{summary}</p>
        </div>

        {/* Actions */}
        <div className="fade-up" style={{ display: "flex", gap: "12px", animationDelay: "0.25s" }}>
          <button className="btn btn-primary btn-lg" style={{ flex: 1 }} onClick={onRestart}>
            Practice Again →
          </button>
          <button className="btn btn-ghost btn-lg" onClick={handlePrint} style={{ minWidth: 160 }}>
            📄 Export PDF
          </button>
        </div>
      </div>
    </div>
  );
}
